### PR TITLE
Prettier fixes

### PR DESCRIPTION
**Pull request by atjn**
Prettier was set up with different defaults from our editorconfig. Sorry about that, that is fixed now!

Prettier never ran on .svelte files because of [a bug](https://github.com/prettier/prettier/issues/15079). I have added a workaround for that, so our svelte files now have correct formatting :)

### CODE REVIEW

**Review by DenFlyvendeGed — APPROVED** [review]

**Review by BaBrixx — DISMISSED** [review]
LGTM 🥖

**Review by BaBrixx — DISMISSED** [review]
SLGTM🥖

**Review by BaBrixx — APPROVED** [review]
It still looks good to me🥖

**Review by KamyaPA — APPROVED** [review]
LGTM

**Pull request merged**
