### PR TITLE
Created support for CSS transitions

### LINKED ISSUE #119: [Feature] The GUI should support transitions
### Description
The GUI should support transitions through the existing global CSS loader.

### Reason For Request
The old GUI has transitions for almost all actions of opening and closing different elements.

### PR DESCRIPTION
**Pull request by BaBrixx**
Closes #119

### Changes/Additions:
- Created support for CSS transitions in the global CSS schemes loader
- Implemented transitions on existing buttons and console opening / closing
- Now supporting the _prefers-reduced-motion_ media feature
- Simplified the Console component by removing an unnecessary element

### CODE REVIEW

**Comment by atjn** [comment]
LGTM

**Review by DenFlyvendeGed — APPROVED** [review]
LGTM

**Review by DenFlyvendeGed — APPROVED** [review]
LGTM

**Review by Jesper276 — APPROVED** [review]
LGTMMTGMTMTMGM

**Pull request merged**
