### PR TITLE
Made colors and fonts user customisable 

### LINKED ISSUE #112: [Feature] Fonts should use css variable
### Description
Define a single font for the GUI

### PR DESCRIPTION
**Pull request by BaBrixx**
Closes #112

### Changes/Additions:
~~This is still a draft~~ This is ok to review <3
- Color Settings
- Font Settings
- Generic Tabs type
- Includes testing

### CODE REVIEW

**Comment by NybyDK** [comment]
i would like to quits

**Comment by NybyDK** [comment]
but i am not a quitter

**Review by atjn — APPROVED** [review]
LGTM. Have you created an issue for putting the settings pane into a modal?

**Review by DenFlyvendeGed — APPROVED** [review]
LGTM

**Review by atjn — APPROVED** [review]
LGTM

**Pull request merged**
